# Generated by Django 4.2.23 on 2025-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_rol_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'Administrador de sistema'), ('ADMINISTRADOR', 'Administrador'), ('VETERINARIO', 'Veterinario'), ('RECEPCIONISTA', 'Recepcionista')], max_length=20),
        ),
    ]
