# Generated by Django 4.2.23 on 2025-10-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
