# Generated by Django 4.2.23 on 2025-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloinventario',
            name='nivel_reorden',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
